name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          ENV: ${{secrets.PRD_ENV}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: ENV
          script: |
            cd /home/deploy
            rm -rf og-imager
            git clone https://github.com/MaxwellPereira/og-imager.git
            cd og-imager
            echo "$ENV" > .env
            docker build -t og-imager .
            docker kill og-imager
            docker container rm og-imager
            docker build --name og-imager -dp 3002:3002 og-imager
